config/routes.rb
Rails.application.routes.draw do
  resources :recipe_ingredients
  resources :ingredients
  resources :allergies
  resources :recipes
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/allergy.rb
class Allergy < ApplicationRecord
    belongs_to :user
    belongs_to :ingredient
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
    has_many :recipe_ingredients
    has_many :recipes, through: :recipe_ingredients

    has_many :allergies

    def allergic_user_count
        self.allergies.count
    end
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_ingredients, dependent: :destroy
  has_many :ingredients, through: :recipe_ingredients
  accepts_nested_attributes_for :ingredients_attributes
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient
end

app/models/user.rb
class User < ApplicationRecord
    has_many :recipes, dependent: :destroy
    has_many :allergies, dependent: :destroy
    accepts_nested_attributes_for :allergies
end

app/controllers/allergies_controller.rb
class AllergiesController < ApplicationController

    def index
        @allergies = Allergy.all
        # # below for testing purposes
        # @ingredients = Ingredient.all
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

    def index
        @ingredients = Ingredient.all.sort {|ia, ib| ia.allergic_user_count <=> ib.allergic_user_count}.reverse
    end

    def show
        @ingredient = Ingredient.find(params[:id])
    end

    def new
        @ingredient = Ingredient.new
    end

    def create
        @ingredient = Ingredient.new(ingredient_params)
        @ingredient.save
        redirect_to ingredient_path(@ingredient)
    end

    private

    def ingredient_params
        params.require(:ingredient).permit(:name)
    end


end

app/controllers/recipe_ingredients_controller.rb
class RecipeIngredientsController < ApplicationController
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

    def index
        @recipes = Recipe.all
    end

    def show
        @recipe = Recipe.find(params[:id])
    end

    def new
        @recipe = Recipe.new
        3.times {@recipe.ingredients.build}
    end

    def create
        byebug
        # ingr1 = Ingredient.find_or_create_by(name: recipe_params[:recipe][:ingredients_attributes][0])
        # ingr2 = Ingredient.find_or_create_by(name: recipe_params[:recipe][:ingredients_attributes][1])
        # ingr3 = Ingredient.find_or_create_by(name: recipe_params[:recipe][:ingredients_attributes][2])
        @recipe = Recipe.new(recipe_params)
        @recipe.save
        redirect_to recipe_path(@recipe)
    end

    private

    def recipe_params
        params.require(:recipe).permit(:name, :user_id, :ingredients_attributes => [])
    end

end


#, :ingredients_attributes => []

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def index
        @users = User.all
    end

    def show
        @user = User.find(params[:id])
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        @user.save
        redirect_to user_path(@user)
    end

    def destroy
        @user = User.find(params[:id])
        @user.destroy
        redirect_to users_path
    end

    private

    def user_params
        params.require(:user).permit(:name)
    end

end

app/helpers/allergies_helper.rb
module AllergiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipe_ingredients_helper.rb
module RecipeIngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/allergies/index.html.erb
<h1>Allergy Index Page</h1>


<div>
<div>
<h3>Allergies:</h3>
<ul><% @allergies.each do |allergy| %>
    <li><%= link_to(allergy.name, allergy_path(allergy)) %></li>
    <% end %>
</ul>
</div>

app/views/ingredients/_form.html.erb
<h3>Form for New Ingredient</h3>

<%= form_for @ingredient do |f| %>

    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.submit %>
<% end %>

app/views/ingredients/index.html.erb
<h1>Ingredient Index Page</h1>

<h3>Ingredients:</h3>
<ul><% @ingredients.each do |ingredient| %>
    <li><%= link_to(ingredient.name, ingredient_path(ingredient))%> - <%= pluralize(ingredient.allergic_user_count, 'Allergic User') %></li>
    <% end %>
</ul>

<h3>New Ingredient:</h3>
<%= button_to("New Ingredient", new_ingredient_path, method: :get) %>

app/views/ingredients/new.html.erb
<h1>New Ingredient Page</h1>

<%= render "form" %>

app/views/ingredients/show.html.erb
<h1>Ingredient Show Page</h1>

<h3>Name:</h3>
<%= @ingredient.name %>
<br>
<h3>Recipes:</h3>
<ul><% @ingredient.recipes.each do |recipe| %>
    <li><%= link_to(recipe.name, recipe_path(recipe)) %></li>
    <% end %>
</ul>

<h3>TESTING - Allergic Users:</h3>
<ul><% @ingredient.allergies.each do |allergy| %>
    <li><%= link_to(allergy.user.name, user_path(allergy.user)) %></li>
    <% end %>
</ul>

<h3>Back to Index:</h3>
<%= button_to("Index", ingredients_path, method: :get) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/_form.html.erb
<h3>New Recipe Form</h3>

<%= @recipe %>
<%= @recipe.ingredients.count %>

<%= form_for @recipe do |f| %>
 
<%= f.label "Recipe Name" %>
  <%= f.text_field :name %><br>
<br>
  <%= f.fields_for :ingredients do |ingredient| %>
    <%= ingredient.label "Ingredient Name" %>
    <%= ingredient.text_field :name %><br>
  <% end %>
<br>
User Creating This Recipe:<br>
  <%= f.collection_select(:user_id, User.all, :id, :name) %>

<br>
<br>
  <%= f.submit %>
<% end %>


<%= params.inspect %>

app/views/recipes/index.html.erb
<h1>Recipe Index Page</h1>

<h3>Recipes:</h3>
<ul><% @recipes.each do |recipe| %>
    <li><%= link_to(recipe.name, recipe_path(recipe)) %></li>
    <% end %>
</ul>

<h3>New Recipe:</h3>
<%= button_to("New Recipe", new_recipe_path, method: :get) %>

app/views/recipes/new.html.erb
<h1>New Recipe Page</h1>

<%= render "form" %>

app/views/recipes/show.html.erb
<h1>Recipe Show Page</h1>

Recipe name:
<%= @recipe.name %>
<br>

Created by:
<%= @recipe.user.name %>

app/views/users/_form.html.erb
<h3>Form for New User</h3>

<%= form_for @user do |f| %>

    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.submit %>
<% end %>

app/views/users/index.html.erb
<h1>User Index Page</h1>

<h3>Users:</h3>
<ul><% @users.each do |user| %>
    <li><%= link_to(user.name, user_path(user)) %></li>
    <% end %>
</ul>

<h3>New User:</h3>
<%= button_to("New User", new_user_path, method: :get) %>

app/views/users/new.html.erb
<h1>New User Page</h1>

<%= render "form" %>

app/views/users/show.html.erb
<h1>User Show Page</h1>

<h3>Name:</h3>
<%= @user.name %>
<br>
<h3>Recipes:</h3>
<ul><% @user.recipes.each do |recipe| %>
    <li><%= recipe.name %></li>
    <% end %>
</ul>

<h3>Allergies:</h3>
<ul><% @user.allergies.each do |allergy| %>
    <li><%= link_to(allergy.ingredient.name, ingredient_path(allergy.ingredient)) %></li>
    <% end %>
</ul>


<h3>Back to Index:</h3>
<%= button_to("Index", users_path, method: :get) %>
<h3>Back to Index:</h3>
<%= button_to("Delete User", user_path(@user), method: :delete) %>